language: python

sudo: required

dist: bionic

python:
    - 3.8

install:
    - pip install pipenv
    - pipenv install --dev

    - pip install codecov
    - pip install pytest-cov

script:
    - python -m pytest --cov=./tkgbot

after_success:
    - codecov
