language: python

services:
    - docker

sudo: required

python:
    - 3.6

before_install:
    openssl aes-256-cbc -K $encrypted_30e98ec1cee5_key -iv $encrypted_30e98ec1cee5_iv -in scripts/id_rsa.enc -out scripts/id_rsa -d && chmod 400 scripts/id_rsa

install:
    - echo "|1|zFoi3NWuNMfPjYTElAfUMvx1AsU=|SoWJXLqRYTs/B5c2ikNFsm4RCzs= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBMIM1KPTai7TeWpm+lhTkdkhqbasli1qqEHDOpmxFM83HPPe9IOcDgGjBS1sm3tbhL2nK2sjE+vOLZsH2TbPx1Y=" >> $HOME/.ssh/known_hosts
    - pip install pipenv
    - pipenv install --dev

script:
    - python -m pytest

deploy:
    on:
        branch: develop
    skip_cleanup: true
    provider: script
    script: 
        bash scripts/build_docker_image.sh;
        bash scripts/deploy.sh
